sudo su - -c "R -e \"install.packages('ada', repos = 'http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('rpart', repos = 'http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('pROC', repos = 'http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('plyr', repos = 'http://cran.rstudio.com/')\""
sudo su - -c "R -e \"install.packages('kknn', repos = 'http://cran.rstudio.com/')\""